---
title: "Prepare Genotype Data for Imputation - README"
author: "Prepare Genotype Data for Imputation"
date: "2/22/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tasks
A consistent QC is performed across all 5 of our cohorts (e.g. ichip123456_eur, ichip123456_all, ichip7_eur, ichip7_all, bbc). The QC is broken down into three steps. 
- Part 1 Identifies QC issues
- Part 2 Fixes and applies QC parameters
- Part 3 Re-Checks genotype data post QC Changes

The QC thresholds applied are as follows:  

1. Sex Checks were perfomed
    + If PED sex 0 and F < 0.4 updated PED to Female 2
    + If PED sex 0 and F > 0.8 update PED to male 1 e
    + samples that have out of range F were removed using F < 0.4 = female and F > 0.8 male. 
2. Identical samples were removed
    + all pairs of individuals with an IBD >=0.8 identified 
    + individual in the pair with the lower genotyping rate removed
3. Markers were filtered for missigness, maf and HWE
    + --geno 0.03 
    + --maf 0.01 
    + --hwe 0.000001
4. Samples were filtered for missigness 
    + --mind 0.03
5. Samples with outlying heterozygoisty were filterd
    + if cohort > 1000 samples uses `mean(imiss_het$obs_het_rate)+(4*sd(imiss_het$obs_het_rate)`
    + if cohort < 1000 samples uses `mean(imiss_het$obs_het_rate)+(3*sd(imiss_het$obs_het_rate)`
